name: Generate docs

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'README.md' ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Generate API documentation
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      run: |
        VERSION=$(git tag --sort=committerdate | tail -1)
        echo Generating API documentation for version $VERSION
        gradle :kmmbeacons:dokkaHtml
    - name: Deploy API documentation to Github Pages
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: kmmbeacons/build/dokka/html
